#!/bin/bash

set -exuo pipefail

if [ "${AWS_ECR_LOGIN-1}" = 1 ] ; then
    eval $(aws ecr get-login)
fi
if [ -n "${DOCKER_REGISTRY_USER-}" ]; then
    docker login -u ${DOCKER_REGISTRY_USER} -p ${DOCKER_REGISTRY_PASS} ${DOCKER_REGISTRY}
fi

docker-compose pull
docker-compose build
docker-compose up -d
eval ${1}

if [ -z ${DOCKER_REGISTRY_TAG+x} ]; then
    exit 0
fi
if [ -z ${DOCKER_REGISTRY_TAG} ]; then
    DOCKER_REGISTRY_TAG=$short_commit
fi
/push.py "${DOCKER_REGISTRY_TAG}"
